config/routes.rb
Rails.application.routes.draw do

  root 'iqe#index'
  get 'create' => 'create#index'
  post 'create' => 'create#save'
  patch 'create' => 'create#save'

  get 'taketest/:license_key' => 'qtest#index', as: :qtest
  patch 'taketest/:license_key' => 'qtest#save'

  get 'taketest' => 'license#no_license'
  post 'taketest' => 'license#license'

  get 'invalid_license' => 'qtest#invalid'
  get 'multi_license_finished' => 'qtest#multi_license_finished'
  get 'path0' => 'qtest#path0'

  get 'promo' => 'promo#index'
  post 'promo' => 'promo#save'
  patch 'promo' => 'promo#save'

  get 'group' => 'iqe#group'
  get 'about' => 'iqe#about'
  get 'contact' => 'iqe#contact'

  get 'report/:password' => 'report#index'
  get 'invalid_password' => 'report#invalid_password'

  get 'question' => 'question#index'

  get 'trigger' => 'trigger#index'

  get 'weight' => 'weight#index'

  get 'innovation' => 'innovation#index'

  get 'version' => 'version#index'

  get 'dump/:password' => 'dump#index'

  get '*path' => 'iqe#unknown'

end

app/controllers/promo_controller.rb
# controller to create promotional licenses
class PromoController < ApplicationController
  def index
    @qtest = Qtest.new(license_key: new_license)
  end

  def save
    @qtest = Qtest.new(license_key: params[:qtest][:license_key],
                       first_name: params[:qtest][:first_name],
                       last_name: params[:qtest][:last_name],
                       email: params[:qtest][:email],
                       coach_first_name: ENV['IQE_COACH_FIRST'],
                       coach_last_name: ENV['IQE_COACH_LAST'],
                       coach_email: ENV['IQE_COACH_EMAIL'],
                       send_to_client: true,
                       free_test: true,
                       major_version: 0,
                       minor_version: 0,
                       unused: true,
                       license_key_sent: false,
                       question_finished: 0)
    errors = !@qtest.valid?
    if params[:qtest][:password] != ENV['IQE_ADMIN_PASSWORD']
      @qtest.errors[:password] = 'Incorrect Password'
      errors = true
    end
    @qtest.question_finished = -1
    if errors
      render 'index'
    else
      # Have client start at first page when they take the test,
      # with question_finished = -1
      @qtest.save
      IqeMailer.promo_to_client_email(@qtest).deliver
    end
  end

  private

  def new_license
    key_in_integers = ([2**16] * 4).map { |number| rand(number) }
    key_in_hex = key_in_integers.map { |number| format('%04X', number) }
    key = key_in_hex.join('-')
    Qtest.exists?(license_key: key) ? new_license : key
  end
end

app/views/promo/_id_info.html.erb
<%= form_for @qtest, url: promo_path, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @qtest.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@qtest.errors.count, 'error') %> prohibited this form from being
        saved:</h2>
      <ul>
        <% @qtest.errors.full_messages.each do |msg| %>
          <li class='alert fade in alert-danger alert-dismissable'><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='control-group'>
    <%= f.label :first_name, :class => 'control-label' %>
    <div class='controls'>
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :last_name, :class => 'control-label' %>
    <div class='controls'>
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :email, :class => 'control-label' %>
    <div class='controls'>
      <%= f.email_field :email,  :class => 'text_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :password, :class => 'control-label' %>
    <div class='controls'>
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.hidden_field :license_key  %>
  </div>
  <div class='form-actions'>
    <%= f.submit 'Create Promo', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/promo/index.erb
<h1>Innovation Quotient Edge Assessment Promo License Creation Page</h1>

<p>
  Welcome to the promo license creation page. Please provide information for
  the person <i><u>receiving</u></i> the promotional assessment and your
  personal password.</p>
<p></p>
<p>
  The person receiving the assessment will receive a link to the assessment
  via email.
</p>
<p></p>
<%= render 'id_info' %>
<p>
  Oops…If you are here accidentally because you are trying to purchase the
  Innovation Quotient Edge assessment for you, your team, or your clients and the internet
  led you astray, please click
  <a href="https://zh130.infusionsoft.com/app/manageCart/addProduct?productId=35">here</a>.</p>
</p><p><p>
  To contact me (Tamara Kleinberg) or my team, call us at 303.339.0135
</p>

app/views/promo/save.erb
<h3>Promo license Sent</h3>

<p>
  Thank you. The unique link (<%= "#{@qtest.license_key}" %>) for the
  Innovation Quotient Edge assessment will be sent to the following person:
</p><p></p>
<p><%= "#{@qtest.first_name} #{@qtest.last_name}: #{@qtest.email}" %></p>