config/routes.rb
Rails.application.routes.draw do

  root 'iqe#index'
  get 'create' => 'create#index'
  post 'create' => 'create#save'
  patch 'create' => 'create#save'

  get 'taketest/:license_key' => 'qtest#index', as: :qtest
  patch 'taketest/:license_key' => 'qtest#save'

  get 'taketest' => 'license#no_license'
  post 'taketest' => 'license#license'

  get 'invalid_license' => 'qtest#invalid'
  get 'multi_license_finished' => 'qtest#multi_license_finished'
  get 'path0' => 'qtest#path0'

  get 'promo' => 'promo#index'
  post 'promo' => 'promo#save'
  patch 'promo' => 'promo#save'

  get 'group' => 'iqe#group'
  get 'about' => 'iqe#about'
  get 'contact' => 'iqe#contact'

  get 'report/:password' => 'report#index'
  get 'invalid_password' => 'report#invalid_password'

  get 'question' => 'question#index'

  get 'trigger' => 'trigger#index'

  get 'weight' => 'weight#index'

  get 'innovation' => 'innovation#index'

  get 'version' => 'version#index'

  get 'dump/:password' => 'dump#index'

  get '*path' => 'iqe#unknown'

end

app/controllers/create_controller.rb
# controller for creating license keys
class CreateController < ApplicationController
  def index
    @qtest = Qtest.new(coach_first_name: ENV['IQE_COACH_FIRST'],
                       coach_last_name: ENV['IQE_COACH_LAST'],
                       coach_email: ENV['IQE_COACH_EMAIL'],
                       send_to_client: true)
  end

  def save
    @coach_first_name = params[:qtest][:coach_first_name]
    @coach_last_name = params[:qtest][:coach_last_name]
    @coach_email = params[:qtest][:coach_email]
    @company = params[:qtest][:company]
    @license_quantity = params[:qtest][:license_quantity].to_i
    @multiuse_license = (params[:qtest][:multi_license] == '1')
    @send_to_client = (params[:qtest][:send_to_client] == '1')
    @qtest = Qtest.new(coach_first_name: @coach_first_name,
                       coach_last_name: @coach_last_name,
                       coach_email: @coach_email,
                       question_finished: -2)
    errors = !@qtest.valid?
    if params[:qtest][:password] != ENV['IQE_ADMIN_PASSWORD']
      @qtest.errors[:password] = 'Incorrect Password'
      errors = true
    end
    if @license_quantity <= 0
      @qtest.errors[:license_quantity] = 'must be greater than 0'
      errors = true
    end
    if errors
      render 'index'
    else
      if @multiuse_license
        @licenses = [new_license]
        qtest = Qtest.new(license_key: @licenses[0],
                          coach_first_name: @coach_first_name,
                          coach_last_name: @coach_last_name,
                          coach_email: @coach_email,
                          send_to_client: @send_to_client,
                          major_version: 0,
                          minor_version: 0,
                          question_finished: -1,
                          multi_license: @license_quantity,
                          company: @company,
                          unused: true,
                          license_key_sent: false)
        qtest.save
      else
        @licenses = []
        @license_quantity.times do
          @licenses << (license = new_license)
          qtest = Qtest.new(license_key: license,
                            coach_first_name: @coach_first_name,
                            coach_last_name: @coach_last_name,
                            coach_email: @coach_email,
                            send_to_client: @send_to_client,
                            major_version: 0,
                            minor_version: 0,
                            question_finished: -1,
                            multi_license: nil,
                            company: @company,
                            unused: true,
                            completed_time: nil,
                            license_key_sent: false)
          qtest.save
        end
      end
      IqeMailer.create_licenses_to_coach_email(@license_quantity,
                                               @licenses,
                                               @send_to_client,
                                               @multiuse_license,
                                               @coach_first_name,
                                               @coach_last_name,
                                               @coach_email).deliver
      if @coach_email != ENV['IQE_COACH_EMAIL']
        IqeMailer.create_licenses_email(@license_quantity,
                                        @licenses,
                                        @send_to_client,
                                        @multiuse_license,
                                        @coach_first_name,
                                        @coach_last_name,
                                        @coach_email).deliver
      end
    end
  end

  private

  def new_license
    key_in_integers = ([2**16] * 6).map { |number| rand(number) }
    key_in_hex = key_in_integers.map { |number| format('%04X', number) }
    key = key_in_hex.join('-')
    Qtest.exists?(license_key: key) ? new_license : key
  end
end

app/views/create/_id_info.html.erb
<%= form_for @qtest, url: create_path, html: {class: 'form-horizontal'} do |f| %>
  <% if @qtest.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@qtest.errors.count, 'error') %>
        prohibited this form from being saved:
      </h2>
      <ul>
        <% @qtest.errors.full_messages.each do |msg| %>
          <li class='alert fade in alert-danger alert-dismissable'>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='control-group'>
    <%= f.label :coach_first_name, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :coach_first_name, class: 'text_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :coach_last_name, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :coach_last_name, class:'text_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :coach_email, class: 'control-label' %>
    <div class='controls'>
      <%= f.email_field :coach_email, class: 'email_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :company, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :company, class: 'text_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :license_quantity, class: 'control-label' %>
    <div class='controls'>
      <%= f.number_field :license_quantity,
                         value: nil,
                         min: 1,
                         class: 'number_field' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :multi_license, class: 'control-label' %>
    <div class='controls'>
      <%= f.check_box :multi_license, class: 'checkbox' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :send_to_client, class: 'control-label' %>
    <div class='controls'>
      <%= f.check_box :send_to_client, class: 'checkbox' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :password, class: 'control-label' %>
    <div class='controls'>
      <%= f.password_field :password, class: 'text_field' %>
    </div>
  </div>
  <div class='form-actions'>
    <%= f.submit 'Create Licenses', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/create/index.erb
<h1>Welcome to the Innovation Quotient Edge Create Licenses Page:</h1>

<h3>
  Please enter the following information for creating a number of new licenses.
</h3>
<%= render 'id_info' %>

app/views/create/save.erb
<% if @multiuse_license %>
  <h1>Here is your multi-use license with <%= @license_quantity %> uses:</h1>
  <h3>
    An email of this license has been sent to
<% else %>
  <h1>Here are your <%= @license_quantity %> licenses:</h1>
  <h3>
    An email of these licenses has been sent to
<% end %>
  <%= "#{@coach_first_name} #{@coach_last_name} <#{@coach_email}>" %>:
</h3>

<p>

</p>
<p></p>
<p></p>
<div>
<% @licenses.each { |license| %>
  <p><%= license %></p>
<% } %>
</div>